edition = "2018"
# comment_width = 60
# condense_wildcard_suffixes = true
# error_on_line_overflow = false
# fn_args_layout = "Tall"
# force_multiline_blocks = true
# format_code_in_doc_comments = true
# format_macro_bodies = true
# format_macro_matchers = true
# imports_layout = "HorizontalVertical"
# match_block_trailing_comma = true
# max_width = 79
# merge_imports = true
# normalize_doc_attributes = true
# overflow_delimited_expr = true
# use_field_init_shorthand = true
# use_try_shorthand = true
# wrap_comments = true
