default_flags = ""

[skin]
input = "none none"

[[verbs]]
invocation = "edit"
key = "enter"
shortcut = "e"
execution = "$EDITOR {file}"

[[verbs]]
key = "ctrl-o"
execution = ":back"

[[verbs]]
key = "alt-i"
execution = ":toggle_hidden"

[[verbs]]
key = "ctrl-c"
execution = ":quit"

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
execution = "git diff {file}"

[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"

[[verbs]]
invocation = "top"
key = "ctrl-y"
execution = ":select_first"

[[verbs]]
invocation = "bottom"
key = "ctrl-e"
execution = ":select_last"

[[verbs]]
key = "ctrl-h"
execution = ":parent"

[[verbs]]
key = "ctrl-l"
execution = ":focus"

[[verbs]]
key = "ctrl-j"
execution = ":line_down"

[[verbs]]
key = "ctrl-k"
execution = ":line_up"

[[verbs]]
key = "ctrl-d"
execution = ":page_down"

[[verbs]]
key = "ctrl-u"
execution = ":page_up"

[[verbs]]
invocation = "open_directory"
from_shell = true
key = "ctrl-o"
execution = "cd {directory}"
